# THYMELEAF
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mvc.favicon.enabled=true
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
spring.resources.static-locations=classpath:/static/

# TRANSLATED MESSAGES
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# DEAFULT LANGUAGE
spring.web.locale=en

# Deactivate automatic generation
security.user.password: none

# Environment variables declaration
#server.port=${PORT:8080}
bearerToken=${bearerToken}

#enable/diable https
server.ssl.enabled=true
server.ssl.key-store=classpath:bestmovie.jks
server.ssl.key-store-password:${jks}
server.ssl.keyStoreType: JKS
server.ssl.keyAlias: bestmovie
server.port=8443
server.http2.enabled=true


# Debugging
#debug=true
#spring.thymeleaf.mode=DEBUG

